ethereum_rpc = "https://ethereum-hoodi-rpc.publicnode.com"
drosera_rpc = "https://relay.hoodi.drosera.io"
eth_chain_id = 560048
drosera_address = "0x91cB447BaFc6e0EA0F4Fe056F5a9b1F14bb06e5D"

[traps]

[traps.approval_drain]
path = "out/ApprovalDrainTrap.sol/ApprovalDrainTrap.json"
response_contract = "0x459b576Ac3807cDEea823336c2034e567a220A6f"
response_function = "respondToApprovalDrain(address,address,address,uint256,uint256)"
cooldown_period_blocks = 5
min_number_of_operators = 1
max_number_of_operators = 3
block_sample_size = 5
private_trap = true
whitelist = ["0x1D6ADd57454289Fa586cC98bC009ef2C5C879e28"]

# Uncomment this to deploy the TransferEventTrap

# [traps.transfer_event_trap]
# path = "out/TransferEventTrap.sol/TransferEventTrap.json"
# response_contract = "0x183D78491555cb69B68d2354F7373cc2632508C7"
# response_function = "helloworld(string)"
# cooldown_period_blocks = 33
# min_number_of_operators = 1
# max_number_of_operators = 2
# block_sample_size = 10
# private_trap = true
# whitelist = []
